import { ThemeId, ThemeData } from "../types/game.types";

export const themes: Record<ThemeId, ThemeData> = {
  code_vibes: {
    back: "./assets/img/cards/codeVibes/code_vibes_back.svg",
    faces: [
      "./assets/img/cards/codeVibes/code_vibes1.svg",
      "./assets/img/cards/codeVibes/code_vibes2.svg",
      "./assets/img/cards/codeVibes/code_vibes3.svg",
      "./assets/img/cards/codeVibes/code_vibes4.svg",
      "./assets/img/cards/codeVibes/code_vibes5.svg",
      "./assets/img/cards/codeVibes/code_vibes6.svg",
      "./assets/img/cards/codeVibes/code_vibes7.svg",
      "./assets/img/cards/codeVibes/code_vibes8.svg",
      "./assets/img/cards/codeVibes/code_vibes9.svg",
      "./assets/img/cards/codeVibes/code_vibes10.svg",
      "./assets/img/cards/codeVibes/code_vibes11.svg",
      "./assets/img/cards/codeVibes/code_vibes12.svg",
      "./assets/img/cards/codeVibes/code_vibes13.svg",
      "./assets/img/cards/codeVibes/code_vibes14.svg",
      "./assets/img/cards/codeVibes/code_vibes15.svg",
      "./assets/img/cards/codeVibes/code_vibes16.svg",
      "./assets/img/cards/codeVibes/code_vibes17.svg",
      "./assets/img/cards/codeVibes/code_vibes18.svg",
    ],
     players: {
      Blue: "./assets/img/player/blue.svg",
      Orange: "./assets/img/player/orange.svg",
    },
  },

  gaming_theme: {
    back: "./assets/img/cards/gaming/gaming_back.svg",
    faces: [
      "./assets/img/cards/gaming/gaming_card_1.svg",
      "./assets/img/cards/gaming/gaming_card_2.svg",
      "./assets/img/cards/gaming/gaming_card_3.svg",
      "./assets/img/cards/gaming/gaming_card_4.svg",
      "./assets/img/cards/gaming/gaming_card_5.svg",
      "./assets/img/cards/gaming/gaming_card_6.svg",
      "./assets/img/cards/gaming/gaming_card_7.svg",
      "./assets/img/cards/gaming/gaming_card_8.svg",
      "./assets/img/cards/gaming/gaming_card_9.svg",
      "./assets/img/cards/gaming/gaming_card_10.svg",
      "./assets/img/cards/gaming/gaming_card_11.svg",
      "./assets/img/cards/gaming/gaming_card_12.svg",
      "./assets/img/cards/gaming/gaming_card_13.svg",
      "./assets/img/cards/gaming/gaming_card_14.svg",
      "./assets/img/cards/gaming/gaming_card_15.svg",
      "./assets/img/cards/gaming/gaming_card_16.svg",
      "./assets/img/cards/gaming/gaming_card_17.svg",
      "./assets/img/cards/gaming/gaming_card_18.svg"
    ],
     players: {
      Blue: "./assets/img/player/blue_pawn.svg",
      Orange: "./assets/img/player/orange_pawn.svg",
    },
  },

  da_projects_theme: {
    back: "./assets/img/cards/dAProject/dA_back.svg",
    faces: [
      "./assets/img/cards/dAProject/dA_card1.svg",  
      "./assets/img/cards/dAProject/dA_card2.svg",
      "./assets/img/cards/dAProject/dA_card3.svg",
      "./assets/img/cards/dAProject/dA_card4.svg",
      "./assets/img/cards/dAProject/dA_card5.svg",
      "./assets/img/cards/dAProject/dA_card6.svg",
      "./assets/img/cards/dAProject/dA_card7.svg",
      "./assets/img/cards/dAProject/dA_card8.svg",
      "./assets/img/cards/dAProject/dA_card9.svg",
      "./assets/img/cards/dAProject/dA_card10.svg",
      "./assets/img/cards/dAProject/dA_card11.svg",
      "./assets/img/cards/dAProject/dA_card12.svg",
      "./assets/img/cards/dAProject/dA_card13.svg",
      "./assets/img/cards/dAProject/dA_card14.svg",
      "./assets/img/cards/dAProject/dA_card15.svg",
      "./assets/img/cards/dAProject/dA_card16.svg",
      "./assets/img/cards/dAProject/dA_card17.svg",
      "./assets/img/cards/dAProject/dA_card18.svg"
    ],
     players: {
      Blue: "./assets/img/player/blue_pawn.svg",
      Orange: "./assets/img/player/orange_pawn.svg",
    },
  },

  foods_theme: {
    back: "./assets/img/cards/food/food_back.svg",
    faces: [
      "./assets/img/cards/food/food_card_1.svg",
      "./assets/img/cards/food/food_card_2.svg",
      "./assets/img/cards/food/food_card_3.svg",
      "./assets/img/cards/food/food_card_4.svg",
      "./assets/img/cards/food/food_card_5.svg",
      "./assets/img/cards/food/food_card_6.svg",
      "./assets/img/cards/food/food_card_7.svg",
      "./assets/img/cards/food/food_card_8.svg",
      "./assets/img/cards/food/food_card_9.svg",
      "./assets/img/cards/food/food_card_10.svg",
      "./assets/img/cards/food/food_card_11.svg",
      "./assets/img/cards/food/food_card_12.svg",
      "./assets/img/cards/food/food_card_13.svg",
      "./assets/img/cards/food/food_card_14.svg",
      "./assets/img/cards/food/food_card_15.svg",
      "./assets/img/cards/food/food_card_16.svg",
      "./assets/img/cards/food/food_card_17.svg",
      "./assets/img/cards/food/food_card_18.svg"
    ],
     players: {
      Blue: "./assets/img/player/blue_pawn.svg",
      Orange: "./assets/img/player/orange_pawn.svg",
    },
  },
};
